version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 7cards
      POSTGRES_USER: ostin
      POSTGRES_PASSWORD: 4101641016
    ports:
      - '5433:5432'
    networks:
      - shared_network
    restart: always

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    networks:
      - shared_network
    restart: always

  backend:
    build: ../
    volumes:
      - ./app:/usr/src/app
    ports:
      - '3000:3000'
    env_file: ../.env.prod
    depends_on:
      - db
      - redis
    networks:
      - shared_network

volumes:
  postgres-data:
  redis-data:

networks:
  shared_network:
    external: true
