version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 7cards
      POSTGRES_USER: ostin
      POSTGRES_PASSWORD: 4101641016
    ports:
      - '5432:5432'
    restart: always

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    restart: always

  app:
    build: ../
    volumes:
      - ./app:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://ostin:4101641016@db:5432/7cards?schema=public
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ostin
      DB_PASSWORD: 4101641016
      DB_NAME: 7cards

      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always

volumes:
  postgres-data:
  redis-data:
