version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 7cards
      POSTGRES_USER: ostin
      POSTGRES_PASSWORD: 4101641016
    ports:
      - '5432:5432'
    restart: always

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
    restart: always

  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://ostin:4101641016@localhost:5432/7cards?schema=public
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./app/public:/var/www/html
    depends_on:
      - app
    restart: always

volumes:
  postgres-data:
  redis-data:
